name: Tests

on:
  push:
    branches:
      - '**'
    paths:
      - 'fotoX/**'
      - '.github/workflows/tests.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'fotoX/**'
      - '.github/workflows/tests.yml'

jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      
      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/swiftpm/org.swift.swiftpm
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Run Unit Tests
        run: |
          set -euo pipefail

          xcodebuild test \
            -project fotoX/fotoX.xcodeproj \
            -scheme fotoX \
            -destination 'platform=iOS Simulator,name=iPad Air 13-inch (M3)' \
            -only-testing:fotoXTests \
            -resultBundlePath UnitTests.xcresult \
            -quiet

      - name: Publish Unit Test Results
        uses: kishikawakatsumi/xcresulttool@v1
        if: success() || failure()
        with:
          path: UnitTests.xcresult
          title: Unit Tests
          show-passed-tests: false
          show-code-coverage: false
          upload-bundles: failure


  ui-tests:
    runs-on: macos-latest
    if: >
      github.event_name == 'pull_request' &&
      github.base_ref == 'main'

    steps:
      - uses: actions/checkout@v5

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/swiftpm/org.swift.swiftpm
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Run UI Tests
        run: |
          set -euo pipefail

          xcodebuild test \
            -project fotoX/fotoX.xcodeproj \
            -scheme fotoX \
            -destination 'platform=iOS Simulator,name=iPad Air 13-inch (M3)' \
            -only-testing:fotoXUITests \
            -resultBundlePath UITests.xcresult \
            -quiet

      - name: Publish UI Test Results
        uses: kishikawakatsumi/xcresulttool@v1
        if: success() || failure()
        with:
          path: UITests.xcresult
          title: UI Tests
          show-passed-tests: false
          show-code-coverage: false
          upload-bundles: failure
